### ISSUE TITLE
Making friendly micro services - DockerCon 2016 [37m28s]

### ISSUE THREAD

**Issue by crccheck** [CondeNast/atx-lunchnlearn#11]
Probably the best video on microservices I've seen in a long time that's. I like how it isn't just an intro to what microservices are. Although it's a DockerCon talk, no Docker knowledge required.

https://www.youtube.com/watch?v=zRg7pIS3TjM

**Comment by stripethree** [comment]
Needs 🔗 !

**Comment by crccheck** [comment]
added!

**Comment by crccheck** [comment]
watched
