### ISSUE TITLE
Discussion of values-based seniority within Condé

### ISSUE THREAD

**Issue by tswicegood** [CondeNast/atx-lunchnlearn#22]
I was part of the working group that fleshed out the new [values-based seniority documentation](https://github.com/CondeNast/docs) internally. I've had a few conversations with folks in the ATX office about these. The idea here is to lead a broader discussion amongst all of the teams outlining the new seniority system and its effect.

**Comment by crccheck** [comment]
Would talking about imposter syndrome be relevant?

**Comment by tswicegood** [comment]
I always love talking about imposter syndrome! :-)

**Comment by ghvaldez** [comment]
My response to that is....Fake it till you make it!

**Comment by nosamanuel** [comment]
Presented previously with @NegaMorgan.
