### ISSUE TITLE
Functional programming design patterns by Scott Wlaschin

### ISSUE THREAD

**Issue by dadeg** [CondeNast/atx-lunchnlearn#25]
My Comments:
This may be a good talk for those interested in functional programming core principles. This may help in a React app, for instance. 

Summary:
In object-oriented development, we are all familiar with design patterns such as the Strategy pattern and Decorator pattern, and design principles such as SOLID. The functional programming community has design patterns and principles as well. This talk will provide an overview of some of these, and present some demonstrations of FP design in practice.

https://www.youtube.com/watch?v=E8I19uA-wGY

**Comment by tswicegood** [comment]
This sounds awesome!

**Comment by crccheck** [comment]
sorry @dadeg, we watched without you! You'll have to watch it like a mono-id.
