### ISSUE TITLE
Ben Chestnut on MailChimp's creative culture

### ISSUE THREAD

**Issue by nosamanuel** [CondeNast/atx-lunchnlearn#30]
https://vimeo.com/34081566 (42:02).

> Ben is the CEO and co-founder of MailChimp.com, one of the most successful e-mail marketing companies around, with over 1.2 million users. They were recently featured in "Fast Company" for their non-traditional corporate culture and creative environment. In this Creative Mornings presentation, Ben talks about the history of the company and what he does as a manager to cultivate such a creative culture. You DON'T want to miss this!

**Comment by nosamanuel** [comment]
I watched this one already and really liked it.

**Comment by crccheck** [comment]
We liked it! So good.
![](https://i2.wp.com/www.plugou.com/wp-content/uploads/2017/04/jurassic-world_plugou_26-04-2017.jpg?resize=1000%2C472)
