### ISSUE TITLE
Hewitt, Meijer and Szyperski: The Actor Model (everything you wanted to know...)

### ISSUE THREAD

**Issue by nosamanuel** [CondeNast/atx-lunchnlearn#35]
https://www.youtube.com/watch?v=7erJ1DV_Tlo (42:33)

> At Lang.NEXT 2012, several conversations happened in the "social room", which was right next to the room where sessions took place. Our dear friend, Erik Meijer, led many interesting conversations, some of which we are fortunate enough to have caught on camera for C9. We'll begin with these Expert to Expert episodes with a "standing" conversation (participants stand comfortably close to the whiteboard) with computer scientists Carl Hewitt, Visiting Professor at Stanford University, creator of the Planner programming language, inventor of the Actor Model (the topic of this conversation), Clemens Szyperski, an MSR scientist working in the Connected Systems Group and Erik.

> What are actors, exactly? No, really. What are they? When is an actor an actor? Everything you wanted to know about actors, but we're afraid to ask... It's all right here. Big thanks to Carl, Clemens and Erik. This is an excellent E2E(2E)!

**Comment by crccheck** [comment]
watched two weeks ago. It was... ok
