### ISSUE TITLE
Minimum Viable Bureaucracy

### ISSUE THREAD

**Issue by nosamanuel** [CondeNast/atx-lunchnlearn#38]
https://air.mozilla.org/minimum-viable-bureaucracy/ (58:46)

As teams grow and projects become more complex, you're going to need a certain amount of process. Or are you? How do you add enough engineering management to be effective without driving engineers crazy?

Join Laura Thomson as she discusses:
Basics of chaordic [sic] systems
Building trust and preserving autonomy
Effective communication practices 
Problem solving in a less-structured environment
Goals, scheduling, and anti-estimation
Shipping and managing scope creep and perfectionism
How to lead instead of merely managing
Emergent process and how to iterate

This talk appeared at OSCON 2013 and the slide deck has garnered some attention, but the talk was not recorded, so as per requests, Laura re-delivers it on Air Mozilla as a brownbag.

**Comment by crccheck** [comment]
watched and recorded and uploaded to `cn-internal-videos`

**Comment by crccheck** [comment]
My (rough) notes:
>
Self organized ducks
Org charts
Book: Sidney Dekker, _The Field Guide to Understanding 'Human Error'_
"Come with code" Most problems can be demoed with code. Avoid bike shedding.
Book: Eric Ries, _The Lean Startup_ /mvp
Anti estimation, do hardest first
Not in this iteration
Leaders should transmit goals
Servant leaders
