### ISSUE TITLE
How to Write Documentation for People that Don't Read

### ISSUE THREAD

**Issue by nosamanuel** [CondeNast/atx-lunchnlearn#39]
https://www.youtube.com/watch?v=sQP_hUNCrcE (28:52)

It's 3AM, do you know where your users are? If people want to learn how to use your product, where are they looking for help? Are they on your site, and if they're on your site, are they finding the right page?

Usability researchers have known for decades that users don't read word by word - they scan for the content they want.

If users can't make heads or tails of your documentation, they'll give up (a loss of revenue), remain ignorant of product features (another loss of revenue) or ask needless support questions (an increased cost).

In this talk we'll examine the findability of your documentation, and the text on the pages in your documentation. We'll examine usability research into how users read, look at several ways your documentation is failing busy users, and the lessons I learned conducting user tests at Twilio. We'll learn more about how users find the answers they are looking for, and the importance of spreading clear writing across not just your documentation, but your headlines and error messages in your API.

**Comment by crccheck** [comment]
![](http://media.tmz.com/2016/02/06/0206-derek-zoolander-vh1-films-paramount-pictures-4.jpg)

**Comment by crccheck** [comment]
1. pretty useful information about documentation
2. wasn't very applicable for our internal docs tho
3. zoom video streaming was pretty ok, worth doing again but very jpeg

**Comment by nosamanuel** [comment]
Slides: https://kev.inburke.com/slides/documentation/.
