### ISSUE TITLE
1% Better Every Day - James Clear at Craft + Commerce 2017

### ISSUE THREAD

**Issue by stripethree** [CondeNast/atx-lunchnlearn#40]
https://www.youtube.com/watch?v=mNeXuCYiE0U&feature=youtu.be

I've watched the first 6 minutes and am interested enough to watch more. The true topic revolves around habit formation. Not tech/code/engineering specific.

**Comment by stripethree** [comment]
20 mins in. I still like it, but it seems familiar and/or it's pulling some concepts that we've already heard via other talks. That said, it would be an interesting watch that would leave time for discussion after on how we can apply the concepts to Condé Nast work or other tech things.

**Comment by tswicegood** [comment]
Sounds interesting to me 👍

**Comment by stripethree** [comment]
Watched!
