### ISSUE TITLE
Nina Zakharenko - Memory Management in Python - PyCon 2016 [25m]

### ISSUE THREAD

**Issue by crccheck** [CondeNast/atx-lunchnlearn#46]
From another Slack:
our team just watched this, which was a great overview/explanation of memory management https://www.youtube.com/watch?v=F6u5rhUQ6dU
YouTubePyCon 2016
Nina Zakharenko - Memory Management in Python - The Basics - PyCon 2016

slides https://www.slideshare.net/nnja/memory-management-in-python-the-basics

**Comment by crccheck** [comment]
neat. short and sweet vid about python internals

**Comment by nnja** [comment]
Found your comment while googling around. Thanks for the compliment! 😆
